//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class wi16b087_SensorLogs
    {
        public string Sensorname { get; set; }
        public System.Guid Id { get; set; }
        public int Type { get; set; }
        public double Value { get; set; }
    }
}
