//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SensorApp.SR_ServiceLayer {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="SR_ServiceLayer.IWcfServiceDefinition")]
    public interface IWcfServiceDefinition {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWcfServiceDefinition/GetSensorData", ReplyAction="http://tempuri.org/IWcfServiceDefinition/GetSensorDataResponse")]
        System.Collections.Generic.List<Shared.SensorModel> GetSensorData();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWcfServiceDefinition/GetSensorData", ReplyAction="http://tempuri.org/IWcfServiceDefinition/GetSensorDataResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<Shared.SensorModel>> GetSensorDataAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWcfServiceDefinition/AddSensorData", ReplyAction="http://tempuri.org/IWcfServiceDefinition/AddSensorDataResponse")]
        void AddSensorData(Shared.SensorModel sensorData);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWcfServiceDefinition/AddSensorData", ReplyAction="http://tempuri.org/IWcfServiceDefinition/AddSensorDataResponse")]
        System.Threading.Tasks.Task AddSensorDataAsync(Shared.SensorModel sensorData);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IWcfServiceDefinitionChannel : SensorApp.SR_ServiceLayer.IWcfServiceDefinition, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WcfServiceDefinitionClient : System.ServiceModel.ClientBase<SensorApp.SR_ServiceLayer.IWcfServiceDefinition>, SensorApp.SR_ServiceLayer.IWcfServiceDefinition {
        
        public WcfServiceDefinitionClient() {
        }
        
        public WcfServiceDefinitionClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WcfServiceDefinitionClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WcfServiceDefinitionClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WcfServiceDefinitionClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Collections.Generic.List<Shared.SensorModel> GetSensorData() {
            return base.Channel.GetSensorData();
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<Shared.SensorModel>> GetSensorDataAsync() {
            return base.Channel.GetSensorDataAsync();
        }
        
        public void AddSensorData(Shared.SensorModel sensorData) {
            base.Channel.AddSensorData(sensorData);
        }
        
        public System.Threading.Tasks.Task AddSensorDataAsync(Shared.SensorModel sensorData) {
            return base.Channel.AddSensorDataAsync(sensorData);
        }
    }
}
